language: php
sudo: false
dist: trusty
php:
  - "7.3"
  - "7.4"
  - "8.0"

before_install:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source

jobs:
  include:
    - script: ./vendor/bin/php-cs-fixer fix . --dry-run --stop-on-violation
    - script: ./vendor/bin/phpstan analyse ./src --level=max
    - script: ./vendor/bin/phpunit
